### ISSUE TITLE
bug report errors (screenshot)

### ISSUE THREAD

**Issue by spirillen** [Phishing-Database/.github#6]
## screenshot

Here are missing 2 blank lines, make them exactly as 

Right way

https://github.com/Phishing-Database/.github/blob/49742617c49827db83849169394675a8868542b1/.github/ISSUE_TEMPLATE/02-bug.yml?plain=1#L74-L78

Wrong way

https://github.com/Phishing-Database/.github/blob/49742617c49827db83849169394675a8868542b1/.github/ISSUE_TEMPLATE/02-bug.yml?plain=1#L80-L81

The right formatted section for screenshot would be like this

```yaml
  - type: textarea
    id: screenshot
    attributes:
      label: Do you have a screenshot?
      description: |
        If applicable to the problem, please provide some screenshots to help explain the problem.

        Please note that there need to be at least one blank line separating before and after the image line.
        To add an image, use the following code: `![Screenshot of Bug](https://example.com/path/to/image.png)`
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: false
```

**Comment by spirillen** [comment]
The right formatting of the full bug report looks like this

```yaml
name: Bug Report
description: Report a bug or issue.
title: BUG | My Awesome Bug
labels:
  - bug
projects:
  - Phishing-Database/2
assignees:
  - funilrys
  - mitchellkrogza
body:
  - type: markdown
    attributes:
      value: |+
        Thanks for taking the time to fill out this bug report!

        All issues are welcome, but please be aware that:
          - We are a small team and may not be able to respond immediately.
          - We may ask for more information to help us understand the issue.
          - Your issue may be moved to one of our other repositories for further investigation.

        We appreciate your help in making the Phishing Database better!

        If you have a question or need help, please ask in our [Discussions](hhttps://github.com/Phishing-Database/dev-center/discussions) section.

        The Phishing Database Project Team.

  - type: textarea
    id: problem
    attributes:
      label: What is the problem you are experiencing?
      description: Please describe the problem you are experiencing.
      placeholder: |
        I am experiencing a problem where...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the problem?
      description: Please describe how we can reproduce the problem.
      value: |
        To reproduce the problem:

        1. 
        2. 
        3. 
        4. 
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Do you have a screenshot?
      description: |
        If applicable to the problem, please provide some screenshots to help explain the problem.

        Please note that there need to be at least one blank line, separating before and after the image line.
        To add an image, use the following code: `![Screenshot of Bug](https://example.com/path/to/image.png)`
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Please describe what you expected to happen.
      placeholder: |
        I expected that...
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Is there a workaround?
      description: Please describe if there is a workaround.
      placeholder: |
        I found a workaround...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Please provide any additional context related to the problem.
      placeholder: |
        I would like to add...
    validations:
      required: false

  - type: textarea
    id: log
    attributes:
      label: Log information
      description: If you have a log file, please paste it here to help trace the issue.
      value: |
        <details><summary>Click to expand</summary>

        ```
        Paste your log file here between the back tics.
        ```

        </details>
    validations:
      required: false
```
